# Generated by Django 5.2.17 on 2026-09-07 21:29

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="nome completo"),
                ),
                (
                    "endereco",
                    models.CharField(max_length=500, verbose_name="endereço completo"),
                ),
                ("telefone", models.CharField(max_length=30, verbose_name="telefone")),
                (
                    "cupom",
                    models.CharField(max_length=50, verbose_name="número do cupom"),
                ),
                (
                    "volumes",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantidade de volumes",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="data da entrega",
                    ),
                ),
                (
                    "horario",
                    models.TimeField(
                        blank=True, null=True, verbose_name="horário previsto"
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="entregador"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="observações"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_rota", "Em rota"),
                            ("entregue", "Entregue"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=12,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("entregue_em", models.DateTimeField(blank=True, null=True)),
                ("versao", models.PositiveIntegerField(default=1)),
                (
                    "requisicao",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="EventoEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=160)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "entrega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="entregas.entrega",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="entrega",
            constraint=models.CheckConstraint(
                condition=models.Q(("volumes__gte", 1)),
                name="entrega_volumes_positivos",
            ),
        ),
    ]
