# Generated by Django 5.2.17 on 2026-09-08 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entregas", "0003_cadastro_entregadores"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrega",
            name="cpf",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{11}$", "Informe os 11 dígitos do CPF."
                    )
                ],
                verbose_name="CPF",
            ),
        ),
    ]
